### ISSUE TITLE
Ticks color change required

### ISSUE THREAD

**Issue by A-jha383** [hack4bengal/hack4bengal.github.io#101]
### Description

In Theme Imagination Section ticks color are matching with text.

### Screenshots

![image](https://user-images.githubusercontent.com/72190187/202209731-2b56d32d-082e-4d78-8104-e7d9e65c0feb.png)

**Comment by A-jha383** [comment]
@Susmita-Dey do the needful

**Comment by Susmita-Dey** [comment]
@A-jha383 I need to match the ticks color with the text colr beside the corresponding ticks.

Right?

**Comment by A-jha383** [comment]
Yes
