### ISSUE TITLE
Add Issue Templates 🛠

### ISSUE THREAD

**Issue by IAmTamal** [hack4bengal/hack4bengal.github.io#17]
## What i am suggesting to add ? 

I am suggesting to add **Issue Templates** to the repository, it can be as many categories as needed - primary categories of issues are mostly : `bugs`, `docs`, `general feature` and so on.

## Why to add it ? 

Adding an issue Template allows you to organize the issues made by folks in a much better way.
 - We can know if someone wants to add a new idea, organize the repository properly !
 - We can know if someone wants to write a test or maybe fix something in the website
 - Here's a general idea : 
 
![image](https://user-images.githubusercontent.com/72851613/192107388-3b5564d1-4efc-4e05-8fd8-ecb271136a77.png)

## Am i able to develop it ? 

Yes, i will be glad to help an Opensource project grow more !

**Comment by imanishbarnwal** [comment]
Hii @IAmTamal, it sounds good to me, you can work on this. Go ahead.

**Comment by IAmTamal** [comment]
## Awesome 🎉 

- Please assign me with the issue
- Please tell the types of templates you'd prefer to have
- `Bugs`, `Documentation Issue`, `Feature Request`, `Other`
- Will be working on it soon !

**Comment by imanishbarnwal** [comment]
For now you can just put these `Bugs, Documentation Issue, Feature Request` I have assigned you this.
