### ISSUE TITLE
Request for discussion forum for this project

### ISSUE THREAD

**Issue by Mohit-Aasirwal** [hack4bengal/hack4bengal.github.io#20]
Request for discussion platform for project so that the project can be discussed extensively.

**Comment by imanishbarnwal** [comment]
Hi @Mohit-Aasirwal, we are already having the `Hacktoberfest Discussion Forum` on our discord server. You may [check here](https://discord.com/channels/920970750154899476/1024245730958909470).

**Comment by Arifafzal51** [comment]
hii please assign me this issue

**Comment by imanishbarnwal** [comment]
Hi @Arifafzal51 we are not planning to work on this issue anymore you can find other issues. I am closing this for now.
