### ISSUE TITLE
Issue with MLH Logo

### ISSUE THREAD

**Issue by prachi1710** [hack4bengal/hack4bengal.github.io#22]
There is an alignment issue with MLH Logo as the navigation menu 'Events' is not completely visible.
![Capture](https://user-images.githubusercontent.com/77247328/192614257-2db32850-7d54-42dd-b084-f31716dbe7e3.PNG)

**Comment by imanishbarnwal** [comment]
Sure @prachi1710, go ahead you may start working on it. Just make sure it's responsive in the mobile version as well. :)
