### ISSUE TITLE
Button Is Not Aligned Properly 

### ISSUE THREAD

**Issue by Mustafa-Azad025** [hack4bengal/hack4bengal.github.io#24]
this is the issue

![image](https://user-images.githubusercontent.com/97380192/192815708-9abd6517-7be3-4353-a73e-3dde035c4665.png)

**Comment by Mustafa-Azad025** [comment]
Will You Assign Me For This Issue.

**Comment by imanishbarnwal** [comment]
Hi @Mustafa-Azad025, it's assigned to you, you may start working on it and send the PR

**Comment by Mustafa-Azad025** [comment]
Hey @imanishbarnwal ,
I have fix issue . Will I Make PR on 1st Oct ??

1440--
![image](https://user-images.githubusercontent.com/97380192/193057624-c2311272-f0ec-4e67-8b2e-99db88d61638.png)
1024--
![image](https://user-images.githubusercontent.com/97380192/193057666-2a7ae484-24d6-468d-bb05-c1f70dc73f22.png)
768--
![image](https://user-images.githubusercontent.com/97380192/193057805-53d58b8b-504d-492a-9aeb-b544cb6c12cd.png)

**Comment by imanishbarnwal** [comment]
Yes do it on or after 1st Oct
