### ISSUE TITLE
Mobile responsiveness - Buttons

### ISSUE THREAD

**Issue by IAmTamal** [hack4bengal/hack4bengal.github.io#27]
## **Describe the bug**

When the website is viewed in mobile, the buttons for about us and MLH code of conducts are stuck to each other. They can be more spaced out vertically !

## **To Reproduce**
1. Go to the Navbar
2. Click on About section
3. See the `MLH Code of conducts` and `About us` stuck to each other 

## **Screenshots**

![image](https://user-images.githubusercontent.com/72851613/193387027-0c7fb774-276e-4171-809b-f53d3cf6deb9.png)

## **Desktop (please complete the following information):**
 - OS: Windows
 - Browser: Chrome
 - Version: 106.0.5249.91

## **Smartphone (please complete the following information):**
 - Device: iphone 12 pro
 - OS: ios
 - Browser: chrome
 - Version: 106.0.5249.75

**Comment by rakeshkumarnahak** [comment]
I would like to work on this issue, please assign me this one.

**Comment by pratham4434** [comment]
I can fix this in no time, please assign this to me!

**Comment by imanishbarnwal** [comment]
Hi @rakeshkumarnahak, you can look for other issues or you can create some other. This is already done and I am closing this issue.
