### ISSUE TITLE
Add carousel arrows around timeline swiper

### ISSUE THREAD

**Issue by janvi01** [hack4bengal/hack4bengal.github.io#30]
**Is your feature request related to a problem? Please describe.**
To enhance user experience, arrows should be there to swipe cards along with dots or we can remove dots.

Screenshot:
<img width="1757" alt="Screenshot 2022-10-01 at 12 42 07 PM" src="https://user-images.githubusercontent.com/34344234/193397836-b1ddb2f4-0605-482f-b092-d5bf2b6a7725.png">

**Comment by imanishbarnwal** [comment]
Hi @janvi01, go ahead...

**Comment by imanishbarnwal** [comment]
Hi @janvi01 this looks good on the desktop but in the mobile version, it's touching the edges which doesn't look good. Also, the arrows should be in the center of the banner. But ig it's not aligned properly could you please fix those? I am also attaching the screenshot for the same.

![image](https://user-images.githubusercontent.com/46371923/194316472-7243d05c-fd71-4178-9f5a-7b20c0a9a11e.png)

**Comment by janvi01** [comment]
Hi, @imanishbarnwal I would create a new PR for this. Thanks!

**Comment by imanishbarnwal** [comment]
Yeah sure please 😇
