### ISSUE TITLE
Use data-purecounter when section comes into view

### ISSUE THREAD

**Issue by developer-diganta** [hack4bengal/hack4bengal.github.io#35]
### What would you like to share?

![image](https://user-images.githubusercontent.com/65999534/193475047-2aa339f7-2ba7-4abc-9104-d0e8a8372c8f.png)
The data-purecounter attribute can be used when the section is in view rather than getting loaded by the time a user comes to that section.

**Comment by imanishbarnwal** [comment]
Didn't get you can you please elaborate?

**Comment by developer-diganta** [comment]
What is happening is when I open the site, say it is at the top view (where the banner for season 2 is there) and by the time I scroll down to the stats section, the data-purecounter has already done its job, so that visual is no more there. What I am trying to say is when a user scrolls to the stats section, the stats should increase from zero to the number. To replicate it, open the page at the stats section and then reload it, the visual is then seen.

**Comment by imanishbarnwal** [comment]
Okay sure, you can work on this but I need visuals once you complete this.

**Comment by imanishbarnwal** [comment]
Thanks @developer-diganta for your contribution!!
