### ISSUE TITLE
logo overflowing  with teams nav and also error in responsiveness

### ISSUE THREAD

**Issue by amitp138** [hack4bengal/hack4bengal.github.io#38]
### Description

mlh logo is coinciding with teams in navbar and also coinciding with the menu in smallar tab 

### Screenshots

![Screenshot (573)](https://user-images.githubusercontent.com/86116926/193732760-b46e7df8-6204-49f8-bf29-dda126a9e35c.png)
![Screenshot (574)](https://user-images.githubusercontent.com/86116926/193732837-532ca333-7b9d-4cd6-b961-cee829c0b5fd.png)

**Comment by amitp138** [comment]
can i start working on this and try to fix this

**Comment by imanishbarnwal** [comment]
Hi @amitp138 this issue is already raised here #22 you may check this and comment there. I am closing this one. Thank you!!
