### ISSUE TITLE
Add alt text to images to improve accessibility and lighthouse score

### ISSUE THREAD

**Issue by developer-diganta** [hack4bengal/hack4bengal.github.io#40]
### Description

The timeline images do not have alt attributes and that affects accessibility as well as decreases light house score.

### Screenshots

![image](https://user-images.githubusercontent.com/65999534/193757111-53f0806c-46eb-48a2-8cf3-5ddeaca7a06f.png)

### Additional information

If it seems legit, can I work on this issue?

**Comment by imanishbarnwal** [comment]
I don't find it relevant. :)

**Comment by developer-diganta** [comment]
Sure!
