### ISSUE TITLE
adding contact us section 

### ISSUE THREAD

**Issue by amitp138** [hack4bengal/hack4bengal.github.io#43]
**Is your feature request related to a problem? Please describe.**
If I have to  ask something or I have query related to the hackathon or mlh then i have copy the mail and open new tab for mailing instead of that if there would be a contact us page where i can directly put my query and my name then it would be very easy to communicate 

**Describe the solution you'd like**
Adding a contact us or a query section or a page in the navbar 
![Screenshot (579)](https://user-images.githubusercontent.com/86116926/193764771-885e9e22-4997-4c53-bcba-8c42183350c6.png)
like above image we can add a contact us page 

**Describe alternatives you've considered**

**Additional context**

**Comment by imanishbarnwal** [comment]
the form is okay how will you link this to the backend?

**Comment by kritiag20** [comment]
I would like to work on this issue

**Comment by amitp138** [comment]
actually we can a simple backend to this in which all the queries can stored

**Comment by amitp138** [comment]
and [kritiag20](https://github.com/kritiag20) if you want we can work upon this together

**Comment by kritiag20** [comment]
ya sure @amitp138

**Comment by amitp138** [comment]
so how we can connect to discuss the changes?

**Comment by imanishbarnwal** [comment]
Hi folks, I don't think we need this we have the discord server for that. You may find some other issues to work on. Thank you!!
