### ISSUE TITLE
Change id of the Themes and Sponsors

### ISSUE THREAD

**Issue by Susmita-Dey** [hack4bengal/hack4bengal.github.io#46]
### Description

Themes and Sponsors in the navbar are linked properly but on hovering I can see their id as something different which is not going wit the names. 

Theme has `id="services"` which should be changed to `"themes"`
Sponsors has `id="portfolio"` which should be changed to `"sponsors"`

I want to change that as part of hacktoberfest and also as part of web dev team of Hack4Bengal 2.0.

### Additional information

Assign it to me.

**Comment by imanishbarnwal** [comment]
Yeah, @Susmita-Dey thanks for pointing. Do the needful. Assigned you. :)

**Comment by deepesh16b** [comment]
assign this to me

**Comment by imanishbarnwal** [comment]
Hey @deepesh16b all the issues are first come first serve you can look for some other issues may be. Thank you :)
