### ISSUE TITLE
Make email and address have links to open in respective apps

### ISSUE THREAD

**Issue by developer-diganta** [hack4bengal/hack4bengal.github.io#52]
### What would you like to share?

The email and address can be made into links so that clicking them will directly open up the required information in respective apps. For example, on clicking the address, google maps may open up with the address on the website.
![image](https://user-images.githubusercontent.com/65999534/193861424-da1c5198-ebc5-4791-b3db-6467cfe1644c.png)

**Comment by imanishbarnwal** [comment]
Okay sure, also change the `Email:` to an Email icon. I guess that will look better.
