### ISSUE TITLE
Need to remove Devfolio button

### ISSUE THREAD

**Issue by imanishbarnwal** [hack4bengal/hack4bengal.github.io#60]
### Description

There is a Devfolio button on the Nav Bar of `Team Page` and `Event Page` we need to remove that. And it should look like the home page's nav bar.

### Screenshots

`Events.html`

![image](https://user-images.githubusercontent.com/46371923/194469957-18235028-d170-4435-aff4-434bd6f82469.png)

`index.html`

![image](https://user-images.githubusercontent.com/46371923/194470004-d5ca7135-9e98-4153-b112-eca432d8430a.png)

**Comment by Teddy1404** [comment]
what exactly to be done can you explain it briefly

**Comment by imanishbarnwal** [comment]
> what exactly to be done can you explain it briefly

Hi can you see a `Go to Dashboard` Button on [Events page](https://hack4bengal.tech/events.html) & [Team page](https://hack4bengal.tech/team.html) which is not there in [main page](https://hack4bengal.tech/index.html) we just need to remove that button

**Comment by kishan-aghera** [comment]
@imanishbarnwal You also mentioned making the navbar in both the `team` and `events` pages the same as the home page, so that change is also needed right, apart from removing the Devfolio button?

**Comment by kishan-aghera** [comment]
Hello. I would like to work on this issue.

**Comment by SugatoBagchi** [comment]
@imanishbarnwal I have already fixed this issue. Can you please assign this issue to me?
