### ISSUE TITLE
Missing community partners

### ISSUE THREAD

**Issue by janvi01** [hack4bengal/hack4bengal.github.io#65]
### Description

On the [main page](https://hack4bengal.tech/), We have plenty of community partners listed.
On [community partners page](https://hack4bengal.tech/community-partners.html), only a few of them are listed.

Solution - 
Add all community partners on https://hack4bengal.tech/community-partners.html

### Screenshots

<img width="1792" alt="Screenshot 2022-10-07 at 12 37 05 PM" src="https://user-images.githubusercontent.com/34344234/194491253-8c5468ac-125c-4514-9aaf-27967fc254e6.png">
<img width="1792" alt="Screenshot 2022-10-07 at 12 37 17 PM" src="https://user-images.githubusercontent.com/34344234/194491315-1220816c-9903-4bbc-830c-1517e878ca8a.png">

**Comment by imanishbarnwal** [comment]
Yes @janvi01 you can work on this but make sure decrease the size of these logo okay. And before sending PRs make sure to drop some screenshots. :)
