### ISSUE TITLE
Change Timeline Date Details

### ISSUE THREAD

**Issue by sagnikmitra** [hack4bengal/hack4bengal.github.io#81]
### Description

Change Timeline Date Details
![Screenshot 2022-10-09 221336](https://user-images.githubusercontent.com/47714127/194769005-278ef775-524a-4f6a-8867-8c78a71d3d5e.png)

Change it to 2023 instead of the existing year i.e. 2022

**Comment by sachin-404** [comment]
Hey, I have changed the timeline kindly take a look!
