### ISSUE TITLE
update contribution.md

### ISSUE THREAD

**Issue by sachin-404** [hack4bengal/hack4bengal.github.io#86]
### Description

I want to add a small contribution guide for beginners (like how to fork, commit, push, etc) in the contribution.md file. Kindly assign this to me.

**Comment by IAmTamal** [comment]
Hi @sachin-404 , we already do have our [Contributing guidelines here](https://github.com/hack4bengal/hack4bengal.github.io/blob/main/CONTRIBUTING.md)

- You can link that file to the main Readme
- You can write some more important steps in a structured manner in the `CONTRIBUTING.md`
- Make sure it looks good.

**Comment by sachin-404** [comment]
#92 

Hi, I have done the changes, kindly have a look

**Comment by sachin-404** [comment]
Hi, I have done the changes, kindly have a look
